name: Testing

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  Fishtest:
    name: linux-avx2
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CXX: clang++
    defaults:
      run:
        working-directory: Rapfi

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          rm -rf build && mkdir build && cd build
          cmake .. -DUSE_SSE=ON -DUSE_AVX2=ON -DUSE_AVX512=OFF -DUSE_BMI2=OFF -DUSE_VNNI=OFF -DNO_COMMAND_MODULES=ON
          cmake --build . -j2 && strip pbrain-rapfi*
          mv -v pbrain-rapfi rapfi-linux-avx2

      - name: Upload to fishtest (freestyle-20)
        if: ${{ contains(github.event.head_commit.message, 'f20') }}
        run: |
          COMMIT_TITLE=$(echo "${{github.event.head_commit.message}}" | head -n 1)
          curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-linux-avx2 -F variant=gomoku_freestyle20 -F "task_name=[f20] $COMMIT_TITLE" -F "password=${{secrets.NOTHING}}" -F "game_time=10" -F "inc_time=0.1" -F "depth=-1" -F "nodes=-1" -F "elo0=0" -F "elo1=5" -F "alpha=0.05" -F "beta=0.05" -F "visible=0"

      - name: Upload to fishtest (freestyle-15)
        if: ${{ contains(github.event.head_commit.message, 'f15') }}
        run: |
          COMMIT_TITLE=$(echo "${{github.event.head_commit.message}}" | head -n 1)
          sleep 10
          curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-linux-avx2 -F variant=gomoku_freestyle15 -F "task_name=[f15] $COMMIT_TITLE" -F "password=${{secrets.NOTHING}}" -F "game_time=10" -F "inc_time=0.1" -F "depth=-1" -F "nodes=-1" -F "elo0=0" -F "elo1=5" -F "alpha=0.05" -F "beta=0.05" -F "visible=0"

      - name: Upload to fishtest (standard-15)
        if: ${{ contains(github.event.head_commit.message, 's15') }}
        run: |
          COMMIT_TITLE=$(echo "${{github.event.head_commit.message}}" | head -n 1)
          sleep 10
          curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-linux-avx2 -F variant=gomoku_standard15 -F "task_name=[s15] $COMMIT_TITLE" -F "password=${{secrets.NOTHING}}" -F "game_time=10" -F "inc_time=0.1" -F "depth=-1" -F "nodes=-1" -F "elo0=0" -F "elo1=5" -F "alpha=0.05" -F "beta=0.05" -F "visible=0"

      - name: Upload to fishtest (renju-15)
        if: ${{ contains(github.event.head_commit.message, 'r15') }}
        run: |
          COMMIT_TITLE=$(echo "${{github.event.head_commit.message}}" | head -n 1)
          sleep 10
          curl http://test.pikafish.org/api/add_task -F engine=@build/rapfi-linux-avx2 -F variant=gomoku_renju15 -F "task_name=[r15] $COMMIT_TITLE" -F "password=${{secrets.NOTHING}}" -F "game_time=10" -F "inc_time=0.1" -F "depth=-1" -F "nodes=-1" -F "elo0=0" -F "elo1=5" -F "alpha=0.05" -F "beta=0.05" -F "visible=0"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Fishtest
          path: Rapfi/build/rapfi-linux-avx2
